### ISSUE TITLE
Error: XML-RPC protocol

### ISSUE THREAD

**Issue by berkipekoglu** [averak/WP_Poster#1]
Hello,
I am getting the following error. I installed all the requirements.

```
Traceback (most recent call last):
  File "C:\Users\Berk\Desktop\WP_Poster-master\post.py", line 4, in <module>
    wp.post_article('deneme', 'deneme içerik', '‪C:/Users/Berk/Desktop/Wallpapers/3439789.jpg')
  File "C:\Users\Berk\Desktop\WP_Poster-master\wp_poster.py", line 16, in post_article
    client = Client(self.url,
  File "C:\Users\Berk\AppData\Local\Programs\Python\Python39\lib\site-packages\wordpress_xmlrpc\base.py", line 23, in __init__
    self.server = xmlrpc_client.ServerProxy(url, allow_none=True, transport=transport)
  File "C:\Users\Berk\AppData\Local\Programs\Python\Python39\lib\xmlrpc\client.py", line 1426, in __init__
    raise OSError("unsupported XML-RPC protocol")
OSError: unsupported XML-RPC protocol
```

**Comment by averak** [comment]
Hello.

Thank you for visiting my repo.
This library is not supposed to be used by anyone other than me.

So, please refer to [python-wordpress-xmlrpc](https://github.com/maxcutler/python-wordpress-xmlrpc).

I'm sorry I can't help you...
